---
production:
  - name: "hub.njrusmc.net"
    role: "hub"
  - name: "site2.njrusmc.net"
    role: "spoke"
  - name: "site3.njrusmc.net"
    role: "spoke"

# For testing only, we can consider the DevNet always-on
# sandboxes to be "spokes" as a quick, cheap means of testing
devnet:
  - name: "ios-xe-mgmt-latest.cisco.com"
    role: "spoke"
  - name: "ios-xe-mgmt.cisco.com"
    role: "spoke"
...
