---
host_list:
  - name: "ios-xe-mgmt-latest.cisco.com"
    role: "hub"

host_list2:
  - name: "hub.njrusmc.net"
    role: "hub"
  - name: "site4.njrusmc.net"
    role: "spoke"
  - name: "site5.njrusmc.net"
    role: "spoke"
...
